#!/usr/bin/env python3
"""
Complete AgileEE Test - Using Full Dataframe with All Fields
"""

import sys, os
sys.path.insert(0, 'agileee')
os.environ['STREAMLIT_LOGGER_LEVEL'] = 'ERROR'

import logging
logging.getLogger().setLevel(logging.ERROR)

import pandas as pd
from agileee.models import predict_man_hours, list_available_models

print("🚀 AgileEE Complete Test - All 13 Projects with Full Feature Set")
print("="*85)

# Your complete data with all fields
data = [
        {
            'project_prf_year_of_project': 2006,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': 'MF',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'COBOL',
            'project_prf_functional_size': 60,
            'functional_size_group': 'S:<100',
            'project_prf_relative_size': 'S',
            'project_prf_normalised_work_effort': 3730,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2009,
            'external_eef_industry_sector': 'Financial',
            'external_eef_organisation_type': 'Financial, Property & Business Services',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'Enhancement',
            'tech_tf_development_platform': 'MF',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'PL/I',
            'project_prf_functional_size': 90,
            'functional_size_group': 'S:<100',
            'project_prf_relative_size': 'S',
            'project_prf_normalised_work_effort': 5831,
            'project_prf_team_size_group': '5-8',
            'project_prf_max_team_size': 8,
            'project_prf_case_tool_used': 'No',
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 13,
            'tech_tf_architecture': 'Stand alone',
            'tech_tf_client_server': 'No',
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': 'Yes',
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': 2,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2012,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Business Application',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': None,
            'tech_tf_language_type': '4GL',
            'tech_tf_primary_programming_language': None,
            'project_prf_functional_size': 63,
            'functional_size_group': 'S:<100',
            'project_prf_relative_size': 'S',
            'project_prf_normalised_work_effort': 1784,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 2,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2006,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'Enhancement',
            'tech_tf_development_platform': 'MF',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'COBOL',
            'project_prf_functional_size': 143,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M1',
            'project_prf_normalised_work_effort': 9566,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2007,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'Enhancement',
            'tech_tf_development_platform': 'PC',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'Visual Basic',
            'project_prf_functional_size': 577,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M2',
            'project_prf_normalised_work_effort': 9382,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2009,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'Enhancement',
            'tech_tf_development_platform': 'MF',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'COBOL',
            'project_prf_functional_size': 271,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M1',
            'project_prf_normalised_work_effort': 2613,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2011,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Business Application',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': None,
            'tech_tf_language_type': '4GL',
            'tech_tf_primary_programming_language': 'Visual Basic',
            'project_prf_functional_size': 160,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M1',
            'project_prf_normalised_work_effort': 989,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 2,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2013,
            'external_eef_industry_sector': 'Financial',
            'external_eef_organisation_type': 'Financial, Property & Business Services',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Business Application',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': None,
            'tech_tf_language_type': '4GL',
            'tech_tf_primary_programming_language': 'Oracle',
            'project_prf_functional_size': 336,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M2',
            'project_prf_normalised_work_effort': 3494,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 2,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2014,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Business Application',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': None,
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'Java',
            'project_prf_functional_size': 958,
            'functional_size_group': 'M:100-999',
            'project_prf_relative_size': 'M2',
            'project_prf_normalised_work_effort': 13200,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 2,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2006,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': 'PC',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'Java',
            'project_prf_functional_size': 1006,
            'functional_size_group': 'L:1000-2999',
            'project_prf_relative_size': 'L',
            'project_prf_normalised_work_effort': 23429,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': 'Web',
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2013,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Mobile Application',
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': 'PC',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'iOS',
            'project_prf_functional_size': 1244,
            'functional_size_group': 'L:1000-2999',
            'project_prf_relative_size': 'L',
            'project_prf_normalised_work_effort': 5773,
            'project_prf_team_size_group': '5-8',
            'project_prf_max_team_size': 8,
            'project_prf_case_tool_used': 'No',
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': 'Client server',
            'tech_tf_client_server': 'Yes',
            'tech_tf_client_roles': 'mobile app',
            'tech_tf_server_roles': 'back-end',
            'tech_tf_type_of_server': 'back-end',
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2009,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': 'Business Application',
            'project_prf_application_type': 'Financial transaction process/accounting',
            'project_prf_development_type': 'Enhancement',
            'tech_tf_development_platform': 'MF',
            'tech_tf_language_type': '3GL',
            'tech_tf_primary_programming_language': 'COBOL',
            'project_prf_functional_size': 1252,
            'functional_size_group': 'L:1000-2999',
            'project_prf_relative_size': 'L',
            'project_prf_normalised_work_effort': 14437,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 3,
            'tech_tf_architecture': None,
            'tech_tf_client_server': None,
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        },
        {
            'project_prf_year_of_project': 2010,
            'external_eef_industry_sector': 'Banking',
            'external_eef_organisation_type': 'Banking',
            'project_prf_application_group': None,
            'project_prf_application_type': None,
            'project_prf_development_type': 'New Development',
            'tech_tf_development_platform': 'Multi',
            'tech_tf_language_type': '4GL',
            'tech_tf_primary_programming_language': '.Net',
            'project_prf_functional_size': 5667,
            'functional_size_group': 'XL:3000-8999',
            'project_prf_relative_size': 'XL',
            'project_prf_normalised_work_effort': 50457,
            'project_prf_team_size_group': None,
            'project_prf_max_team_size': None,
            'project_prf_case_tool_used': None,
            'process_pmf_development_methodologies': 'Agile Development',
            'process_pmf_prototyping_used': None,
            'process_pmf_docs': 2,
            'tech_tf_architecture': 'Client server',
            'tech_tf_client_server': 'Yes',
            'tech_tf_client_roles': None,
            'tech_tf_server_roles': None,
            'tech_tf_type_of_server': None,
            'tech_tf_clientserver_description': None,
            'tech_tf_web_development': None,
            'tech_tf_dbms_used': None,
            'tech_tf_tools_used': None,
            'people_prf_project_user_involvement': None,
            'people_prf_project_manage_changes': None,
            'people_prf_personnel_changes': 0
        }
    ]

# Convert to DataFrame
df = pd.DataFrame(data)
models = list_available_models()

print(f"📋 Testing with {len(models)} models: {[m['display_name'] for m in models]}")
print(f"📊 Dataset: {len(df)} projects with {len(df.columns)} features each\n")

# Clean table header
print("ID  Year  Sector     Language      Size   Actual    GB Pred   LGBM Pred  BR Pred   Error")
print("-"*85)

for idx, row in df.iterrows():
    # Remove target column for prediction
    features = row.drop('project_prf_normalised_work_effort').to_dict()
    actual = row['project_prf_normalised_work_effort']
    
    # Test with all models
    predictions = []
    for model in models:
        try:
            pred = predict_man_hours(features, model['technical_name'])
            predictions.append(pred if pred and pred > 0 else 0)
        except Exception:
            predictions.append(0)
    
    # Calculate average error
    if all(p > 0 for p in predictions):
        avg_pred = sum(predictions) / len(predictions)
        error_pct = abs(avg_pred - actual) / actual * 100
        
        # Format for display
        sector = row['external_eef_industry_sector'][:10]
        lang = row['tech_tf_primary_programming_language'] or 'Unknown'
        lang = lang[:12]
        
        print(f"{idx+1:<3} {row['project_prf_year_of_project']:<5} {sector:<10} {lang:<12} "
              f"{row['project_prf_functional_size']:<6} {actual:<8.0f} "
              f"{predictions[0]:<9.0f} {predictions[1]:<9.0f} {predictions[2]:<9.0f} {error_pct:>6.1f}%")
    else:
        print(f"{idx+1:<3} {row['project_prf_year_of_project']:<5} PREDICTION FAILED")

print("\n🎯 Test Complete!")
print("Legend: GB=Gradient Boosting, LGBM=LightGBM, BR=Bayesian Ridge")

# Summary statistics
print(f"\n📈 Summary:")
print(f"- Total projects tested: {len(df)}")
print(f"- Feature count per project: {len(df.columns)-1} (excluding target)")
print(f"- Models tested: {len(models)}")