numeric_features:
  - project_prf_year_of_project
  - project_prf_functional_size
  - project_prf_max_team_size
  - process_pmf_docs
  - tech_tf_tools_used
  - people_prf_personnel_changes
  - people_prf_project_user_involvement

categorical_features:
  external_eef_industry_sector:
    options: 
      - 
      - Banking
      #- Construction
      #- Defence
      #- Education
      #- Electronics Computers
      - Financial
      #- Government
      #- Insurance
      #- Logistics
      #- Manufacturing
      #- Mining
      #- Medical Healthcare
      #- Professional Services
      #- Service Industry
      #- Telecommunications
      #- Utilities
      #- Wholesale Retail
      #- Other
  external_eef_organisation_type:
    options:
      - 
      #- All industry organization types
      - Amusement/Game Center
      #- Aerospace / Automotive
      - Banking
      - Banking, Insurance, Stock
      #- Biotech
      #- Communications
      #- Community Services
      #- Consumer Foods
      - Credit Card Processor
      #- Education Institution
      #- Electricity, Gas, Water
      #- Energy
      - Financial
      - Financial, Property & Business Services
      #- Food Processing
      #- Government
      #- High Tech
      #- IEEE
      #- Information Technology
      #- Institutions eg. Kindergartens
      - Insurance
      #- Medical & Healthcare
      #- Public Administration
      #- Public Sector
      - Revenue
      - Revenue Collection
      #- Surveillance Security
      #- Transport Storage
      #- Wholesale & Retail Trade
  project_prf_application_type:
    options:
      - 
      #- Airport Management
      #- Analysis Management
      - Accounting System
      - Advertising/Mailing Campaign
      - Application Security Control
      - Auditing Management
      - Automated Customer Statements
      #- Automated Data Acquisition
      - Business Application
      - Cards and Payments
      - Catalogue/Register Of Things Or Events
      - Client Server
      #- Clinical Archive
      #- Complex Process Control
      - Content Management System
      #- Course Management
      #- Customer Billing
      - Customer Billing/Relationship Management
      - Customer Relationship Management
      - Data Or Database Management
      - Data Warehouse System
      - Decision Support System
      - Document Management System
      #- Dynamic Website
      - Electronic Data Interchange
      - Executive Information System
      - Fault Tolerance
      #- Embedded System/Real-time Application
      - Financial Transaction Process/Accounting
      #- Hospital Information System
      - Human Resource Management
      - Identify Management
      - Internet Banking for Customers
      - Job, Case, Incident, Project Management
      #- Logistic/Supply Planning_Control
      - Management/Performance Reporting
      #- Management of Licenses & Permits
      - Management Information System
      - Management System
      - Mathematical Modelling Finance/Eng
      - Mission Critical System
      - Mobile Application
      - Office Automation
      - Office Information System
      #- Online eSales
      - Online Analysis & Reporting
      - Operating System or Software Utility
      - Personal System
      - Personnel System
      - Project Management
      - Promotions
      - Proposal Builder
      - Sales Contact Management
      #- Software Development Tool
      #- Security_Authentication
      #- Security Controls
      - Security Management
      - Software for Machine Control
      #- Student/Tests Management
      - Surveillance & Security
      - System Conversion
      - System Software
      - Telecom & Network Management
      - Transaction/Production System
      - Web Content Management
      - Web Content & Middleware
      - Web-Based Application
      - Workflow Support & Management
  tech_tf_client_roles:
    options:
      - 
      - business logic or rule processing
      - data entry & validation
      - data retrieval & presentation
      - database server
      - device/equipment interface
      - run a computer-human interface
      - security
      - web/html browser
      - web public interface
  tech_tf_server_roles:
    options:
      - 
      - business logic + integration to 30 other systems
      - data acquisation
      - database server
      - file &/or print server
      - ftp server
      - html/web server
      - multi-user legacy application
      - security/authentication
      - mail server
      - messaging server
      - object/component server
  project_prf_application_group:
    options: ["", "Business Application", "Infrastructure Software", "Mathematically Intensive Application", "Real-time Application"]
  project_prf_development_type: 
    options: ["", "Enhancement", "New Development", "Re-development"]
  tech_tf_development_platform:
    options: ["", "Mainframe (MF)", "Midrang (MR)", "Multi-platform", "PC", "Proprietary"]
  tech_tf_language_type:
    options: ["", "2GL (Second Generation)", "3GL (Third Generation)", "4GL (Fourth Generation)", "5GL (Fifth Generation)", "Application Generator", "Other"]
  tech_tf_primary_programming_language:
    options:
      - 
      - ABAP
      - Agile platform
      - JAVA
      - Javascript
      - C
      - C++
      - PL/i
      - Natural
      - Cobol
      - Oracle
      - Proprietary Agile Platform
      - Other
  project_prf_relative_size:
    options:
      - code: ""
        label: ""
        midpoint: null
      - code: XXS
        label: "Extra Extra Small (0–<10)"
        midpoint: 5
        minimumhour: 0
        maximumhour: 200
      - code: XS
        label: "Extra Small (10–<30)"
        midpoint: 20
        minimumhour: 200
        maximumhour: 600
      - code: S
        label: "Small (30–<100)"
        midpoint: 65
        minimumhour: 600
        maximumhour: 2000
      - code: M1
        label: "Medium 1 (100–<300)"
        midpoint: 200
        minimumhour: 2000
        maximumhour: 6000
      - code: M2
        label: "Medium 2 (300–<1000)"
        midpoint: 650
        minimumhour: 6000
        maximumhour: 20000
      - code: L
        label: "Large (1,000–<3,000)"
        midpoint: 2000
        minimumhour: 20000
        maximumhour: 60000
      - code: XL
        label: "Extra Large (3,000–<9,000)"
        midpoint: 6000
        minimumhour: 60000
        maximumhour: 180000
      - code: XXL
        label: "Extra Extra Large (9,000–<18,000)"
        midpoint: 13500
        minimumhour: 180000
        maximumhour: 360000
      - code: XXXL
        label: "Extra Extra Extra Large (≥18,000)"
        midpoint: 18000
        minimumhour: 360000
        maximumhour: 960000 # 500 man-years is too big for any projects, need to be split into smaller projects
  tech_tf_architecture:
    options: ["", "Client-Server", "Multi-tier with Web Interface", "Stand-alone"]
  tech_tf_client_server:
    options: ["", "No", "Yes"]
  tech_tf_web_development:
    options: ["", "No", "Yes"]
  tech_tf_dbms_used:
    options: ["", "No", "Yes"]
  process_pmf_prototyping_used:
    options: ["", "No", "Yes"]
  project_prf_case_tool_used:
    options: ["", "No", "Yes"]
  project_prfcost_currency:
    options: ["", "Canadian Dollar", "European Euro"]
  process_pmf_development_methodologies:
    options:
      - 
      - Agile Development
      - Iterative
      - Joint Application Development (jad)
      - Multifunctional Teams
      - Personal Software Process (psp)
      - Scrum
      - Unified Process
  project_prf_team_size_group:
    options: ["", "1", "2", "3-4", "5-8", "9-14", "15-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100", "101+"]

one_hot_features:
  external_eef_industry_sector:
    input_key: external_eef_industry_sector
    mapping:
      "Banking": external_eef_industry_sector_banking
      "Financial": external_eef_industry_sector_financial
  external_eef_organisation_type:
    input_key: external_eef_organisation_type
    mapping:
      "Amusement/Game Center": external_eef_organisation_type_amusement_game_center
      "Banking": external_eef_organisation_type_banking
      "Banking/Insurance/Stock": external_eef_organisation_type_banking_insurance_stock
      "Credit Card Processor": external_eef_organisation_type_credit_card_processor
      "Financial": external_eef_organisation_type_financial
      "Financial/Property and Business Services": external_eef_organisation_type_financial_property_and_business_services
      "Insurance": external_eef_organisation_type_insurance
      "Missing": external_eef_organisation_type_missing
      "Revenue": external_eef_organisation_type_revenue
      "Revenue Collection": external_eef_organisation_type_revenue_collection
  project_prf_application_group:
    input_key: project_prf_application_group
    mapping:
      "Business Application": project_prf_application_group_business_application
      "Infrastructure Software": project_prf_application_group_infrastructure_software
      "Mathematically Intensive Application": project_prf_application_group_mathematically_intensive_application
      "Real-time Application": project_prf_application_group_real_time_application
  development_type:
    input_key: project_prf_development_type
    mapping:
      "Enhancement": project_prf_development_type_enhancement
      "New Development": project_prf_development_type_new_development
      "Re-development": project_prf_development_type_re_development
  development_platform:
    input_key: tech_tf_development_platform
    mapping:
      "Mainframe (MF)": tech_tf_development_platform_mf
      "Midrang (MR)": tech_tf_development_platform_mr
      "Multi-platform": tech_tf_development_platform_multi
      "PC": tech_tf_development_platform_pc
      "Proprietary": tech_tf_development_platform_proprietary
  language_type:
    input_key: tech_tf_language_type
    mapping:
      "2GL (Second Generation)": tech_tf_language_type_2GL
      "3GL (Third Generation)": tech_tf_language_type_3GL
      "4GL (Fourth Generation)": tech_tf_language_type_4GL
      "5GL (Fifth Generation)": tech_tf_language_type_5GL
      "Application Generator": tech_tf_language_type_application_generator
      "Other": tech_tf_language_type_other
  primary_language:
    input_key: tech_tf_primary_programming_language
    mapping:
      "ABAP": tech_tf_primary_programming_language_abap
      "Agile platform": tech_tf_primary_programming_language_agile_platform
      "JAVA": tech_tf_primary_programming_language_java
      "Javascript": tech_tf_primary_programming_language_javascript
      "C": tech_tf_primary_programming_language_c
      "C++": tech_tf_primary_programming_language_cplusplus
      "PL/i": tech_tf_primary_programming_language_pli
      "Natural": tech_tf_primary_programming_language_natural
      "Cobol": tech_tf_primary_programming_language_cobol
      "Oracle": tech_tf_primary_programming_language_oracle
      "Proprietary Agile Platform": tech_tf_primary_programming_language_proprietary_agile_platform
      "Other": tech_tf_primary_programming_language_other
  project_prf_relative_size:
    input_key: project_prf_relative_size
    mapping:
      "XXS (Extra Extra Small)": project_prf_relative_size_xxs
      "XS (Extra Small)": project_prf_relative_size_xs
      "S (Small)": project_prf_relative_size_s
      "M1 (Medium 1)": project_prf_relative_size_m1
      "M2 (Medium 2)": project_prf_relative_size_m2
      "L (Large)": project_prf_relative_size_l
      "XL (Extra Large)": project_prf_relative_size_xl
      "XXL (Extra Extra Large)": project_prf_relative_size_xxl
      "XXXL (Extra Extra Extra Large)": project_prf_relative_size_xxxl
  tech_tf_architecture:
    input_key: tech_tf_architecture
    mapping:
      "Client-Server": tech_tf_architecture_client_server
      "Multi-tier with Web Interface": tech_tf_architecture_multi_tier_with_web_interface
      "Stand-alone": tech_tf_architecture_stand_alone
  tech_tf_client_server:
    input_key: tech_tf_client_server
    mapping:
      "No": tech_tf_client_server_no
      "Yes": tech_tf_client_server_yes
  tech_tf_web_development:
    input_key: tech_tf_web_development
    mapping:
      "Yes": tech_tf_web_development_yes
      "No": tech_tf_web_development_no
  tech_tf_dbms_used:
    input_key: tech_tf_dbms_used
    mapping:
      "Yes": tech_tf_dbms_used_yes
      "No": tech_tf_dbms_used_no
  project_prfcost_currency:
    input_key: project_prfcost_currency
    mapping:
      "Canadian Dollar": project_prf_cost_currency_canadian_dollar
      "European Euro": project_prf_cost_currency_european_euro
  process_pmf_development_methodologies:
    input_key: process_pmf_development_methodologies
    mapping:
      "Agile Development": process_pmf_development_methodologies_agile_development
      "Iterative": process_pmf_development_methodologies_iterative
      "Joint Application Development (jad)": process_pmf_development_methodologies_joint_application_development_jad
      "Multifunctional Teams": process_pmf_development_methodologies_multifunctional_teams
      "Personal Software Process (psp)": process_pmf_development_methodologies_personal_software_process_psp
      "Scrum": process_pmf_development_methodologies_scrum
      "Unified Process": process_pmf_development_methodologies_unified_process

special_cases:
  team_size_group:
    input_key: project_prf_team_size_group
    options: ["1", "2", "3-4", "5-8", "9-14", "15-20", "21-30", "31-40", "41-50", "51-60", "61-70", "71-80", "81-90", "91-100", "101+", "Missing"]
    output_keys:
      "1": project_prf_team_size_group_1
      "2": project_prf_team_size_group_2
      "3-4": project_prf_team_size_group_3_4
      "5-8": project_prf_team_size_group_5_8
      "9-14": project_prf_team_size_group_9_14
      "15-20": project_prf_team_size_group_15_20
      "21-30": project_prf_team_size_group_21_30
      "31-40": project_prf_team_size_group_31_40
      "41-50": project_prf_team_size_group_41_50
      "51-60": project_prf_team_size_group_51_60
      "61-70": project_prf_team_size_group_61_70
      "71-80": project_prf_team_size_group_71_80
      "81-90": project_prf_team_size_group_81_90
      "91-100": project_prf_team_size_group_91_100
      "101+": project_prf_team_size_group_101plus
      "Missing": project_prf_team_size_group_missing

binary_features:
  prototyping:
    input_key: process_pmf_prototyping_used
    mapping:
      "Yes": process_pmf_prototyping_used_yes
      "No": process_pmf_prototyping_used_no
  case_tool:
    input_key: project_prf_case_tool_used
    mapping:
      "Yes": project_prf_case_tool_used_yes
      "No": project_prf_case_tool_used_no
  web_development:
    input_key: tech_tf_web_development
    mapping:
      "Yes": tech_tf_web_development_yes
      "No": tech_tf_web_development_no
  dbms_used:
    input_key: tech_tf_dbms_used
    mapping:
      "Yes": tech_tf_dbms_used_yes
      "No": tech_tf_dbms_used_no